# Generated by Django 3.1.2 on 2021-03-28 09:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=64, unique=True)),
                ('description', models.TextField(max_length=64, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('date_create', models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата создания комментария')),
                ('date_update', models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата изменения комментария')),
                ('comment_status', models.CharField(blank=True, max_length=3, null=True, verbose_name='Статус комментария')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ответы', to='mainapp.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=64, unique=True)),
                ('text', models.TextField(verbose_name='Содержание')),
                ('post_status', models.CharField(choices=[('Aip', 'Ждет одобрения'), ('Apr', 'Одобрено'), ('Del', 'Удалено'), ('Can', 'Отклоненая'), ('Drf', 'Черновик')], default='Drf', max_length=3)),
                ('status_update', models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата обновления статуса')),
                ('date_create', models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата создания статьи')),
                ('date_update', models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата изменения статьи')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.categorypost', verbose_name='Категория')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512, verbose_name='причина отклонения')),
                ('date_create', models.DateTimeField(default=datetime.datetime.today)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(default=datetime.datetime.today)),
                ('date_update', models.DateTimeField(default=datetime.datetime.today)),
                ('author_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author_like', to=settings.AUTH_USER_MODEL)),
                ('comment_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.comment')),
                ('post_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.post')),
                ('user_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
