# Generated by Django 3.1.2 on 2021-03-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_text',
            field=models.TextField(default='Short_description', verbose_name='Краткое содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='Full_description', verbose_name='Содержание'),
        ),
    ]
