# Generated by Django 3.2 on 2021-05-04 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20210413_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_unlock',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата разблокировки'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislike_authors', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки от пользователей'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(related_name='like_authors', to=settings.AUTH_USER_MODEL, verbose_name='Лайки от пользователей'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
    ]
