# Generated by Django 3.2 on 2021-04-12 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Тег')),
                ('slug', models.CharField(max_length=128, verbose_name='Слаг')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Категория')),
                ('slug', models.CharField(max_length=128, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Статья')),
                ('slug', models.CharField(max_length=256, verbose_name='Слаг')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('short_desc', models.CharField(max_length=512, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('DR', 'Черновик'), ('WT', 'Ожидает одобрения'), ('AP', 'Одобрена'), ('RJ', 'Отклонена')], default='DR', max_length=2, verbose_name='Статус')),
                ('status_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, to='main_app.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date_update'],
            },
        ),
    ]
