# Generated by Django 3.1.2 on 2021-04-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210413_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
