# Generated by Django 3.1.2 on 2021-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210414_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер'),
        ),
    ]
