# Generated by Django 3.2 on 2021-05-04 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_auto_20210418_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('AT', 'Статья'), ('CM', 'Комментарий')], default='AT', max_length=2, verbose_name='Модель')),
                ('model_id', models.IntegerField(verbose_name='ID записи модели')),
                ('text', models.TextField(verbose_name='Жалоба')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('status', models.CharField(choices=[('WT', 'Ожидает рассмотрения'), ('AP', 'Одобрена'), ('RJ', 'Отклонена')], db_index=True, default='WT', max_length=2, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislike_articles', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки от пользователей'),
        ),
        migrations.AddField(
            model_name='article',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='like_articles', to=settings.AUTH_USER_MODEL, verbose_name='Лайки от пользователей'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DR', 'Черновик'), ('WT', 'Ожидает одобрения'), ('AP', 'Одобрена'), ('RJ', 'Отклонена'), ('NF', 'Требует исправления')], default='DR', max_length=2, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('dislikes_count', models.PositiveIntegerField(default=0, verbose_name='Количество дизлайков')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.article', verbose_name='Статья')),
                ('dislikes', models.ManyToManyField(related_name='dislike_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайки от пользователей')),
                ('likes', models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Лайки от пользователей')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.reviews', verbose_name='Родитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
